### ISSUE TITLE
Не удается поймать notify для транзакции

### ISSUE THREAD

**Issue by dapi** [openbill-service/openbill-webhooks#1]
Иду сюда: http://3007.vkontraste.ru/transactions
Кликаю на любой транзакции notify
Затем иду сюда: https://bugsnag.com/brandymint/kiiiosk-dot-com/errors/5757db719f57ff6cb4fad598
Уведомления не поступает

**Comment by dreucodi** [comment]
Надо уведомлять с продакшена.
